apiVersion: v1
kind: Secret
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql-db-init-scripts
stringData:
  90-ml-pipelines-dbinit.sh: |
    mysql -uroot -e "
      GRANT ALL PRIVILEGES ON mlpipeline TO 'mlpipelines'.'%';
      GRANT ALL PRIVILEGES ON cachedb TO 'mlpipelines'.'%';
      GRANT ALL PRIVILEGES ON metadb TO 'mlpipelines'.'%';
      FLUSH PRIVILEGES;"
